runtime: java
env: flex


handlers:
- url: /.*
  script: this field is required, but ignored

runtime_config:
   jdk: openjdk8


resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 0.3
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5